version: '3.6'
services:

  # http://couch429c.davidg.ml:46272/_utils/
  # http://couch429c.david462.tk:46272/_utils/
  # http://listo429c.david462.tk:46272/
  # http://listo429c.david462.tk:46272/
  # http://192.168.88.42:83/
  # http://192.168.88.42:82/l
  # http://192.168.88.42:83/l
  # http://192.168.88.42:82/c/_utils
  # http://192.168.88.42:6216

  couchdb:
    image: couchdb
    volumes:
          - ../data/home429c/:/home                  # folder for exported data, etc.
          - ../datasys/couch429c/:/opt/couchdb/data     #TODO set this
          - ./docker/couchdb/:/opt/couchdb/etc/local.d             
    ports:
        -   "6212:5984" # no ssl
    environment:
      COUCHDB_USER: usera
      COUCHDB_PASSWORD: admin429c
      VIRTUAL_HOST: couch429c.david462.tk      
      VIRTUAL_PORT: 5984      
    networks:
      - sister
  
  listo2:
    # https://github.com/mikechernev/dockerised-php/blob/master/docker-compose.yml
    image:  nginx:1.14 
    volumes:
        - .:/usr/share/nginx/html/l
    ports:
        - "6216:80"
    networks:
      - sister

  proxy1port2:
    image: nginx:1.14   
    ports:
      - "82:3083"
    volumes:
      - ./docker/nginxproxy/upstream1port.conf:/etc/nginx/nginx.conf
    networks:
      - sister
    depends_on:
      - listo2
      - couchdb

  # couchdb2:
    # image: couchdb
    # volumes:
          # - ../datasys/couch429c2/:/opt/couchdb/data     #TODO set this
          # - ./docker/couchdb/:/opt/couchdb/etc/local.d             
    # ports:
        # -   "6217:5984" # no ssl
    # environment:
      # COUCHDB_USER: usera
      # COUCHDB_PASSWORD: admin429c
    # networks:
      # - sister

# https://docs.docker.com/compose/compose-file/#external-1   
networks:
  sister:
    name: sister
      external:true      