version: '3.6'
services:

  listo429c:
    # https://github.com/mikechernev/dockerised-php/blob/master/docker-compose.yml
    image:  nginx:1.15-alpine
    # build:
      # context: ./
      # dockerfile: Dockerfile
    volumes:
        - .:/usr/share/nginx/html
        # - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
        -   "6211:80"
    # links:
        # - "couchdb:couchdb"

  couchdb:
    image: couchdb
    volumes:
          - ../data/home429c/:/home                  # folder for exported data, etc.
          - ../datasys/couch429c/:/opt/couchdb/data     #TODO set this
          - ./docker/couchdb/:/opt/couchdb/etc/local.d             
    ports:
        -   "6212:5984" # no ssl
    environment:
        COUCHDB_USER: usera
        COUCHDB_PASSWORD: admin429c
