version: '3.6'
services:

  couchdb:
    image: couchdb
    volumes:
          - ../data/home429c/:/home                  # folder for exported data, etc.
          - ../datasys/couch429c/:/opt/couchdb/data     #TODO set this
          - ./docker/couchdb/:/opt/couchdb/etc/local.d             
    ports:
        -   "6212:5984" # no ssl
    environment:
      COUCHDB_USER: usera
      COUCHDB_PASSWORD: admin429c
    networks:
      - sister
    environment:
      - VIRTUAL_HOST=couch429c.david462.tk      
      - VIRTUAL_PORT=5984      
    # depends_on:
      # - proxy-upstream

  listo429c:
    # https://github.com/mikechernev/dockerised-php/blob/master/docker-compose.yml
    image:  nginx:1.14 
    # build:
      # context: ./
      # dockerfile: Dockerfile
    volumes:
         - .:/usr/share/nginx/html
        # - .:/usr/share/nginx/html/listo
        # - .:/etc/nginx/html/listo
        # - ./docker/listo/site.conf:/etc/nginx/conf.d/default.conf
    ports:
        # -   "82:80"
        - 80
    # links:
        # - "couchdb:couchdb"
    networks:
      - sister
    environment:
      - VIRTUAL_HOST=listo429c.david462.tk      
      
  # proxy:
    # image: nginx:1.14   
    # ports:
      # - "83:83"
    # volumes:
      # # - ./app:/usr/share/nginx/html
      # - ./docker/nginxproxy/main.conf:/etc/nginx/nginx.conf
      # # - ./docker/nginxproxy/site.conf:/etc/nginx/conf.d/default.conf
    # networks:
      # - sister

  proxy-upstream:
    image: nginx:1.14   
    ports:
      - "84:84"
      - "85:85"
      # - "86:86"
    volumes:
      # - ./app:/usr/share/nginx/html
      - ./docker/nginxproxy/upstream.conf:/etc/nginx/nginx.conf
      # - ./docker/nginxproxy/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sister
    depends_on:
      - listo429c
      - couchdb

      
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "82:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - sister

# https://docs.docker.com/compose/compose-file/#external-1   
networks:
  sister:
    name: sister
      external:true      