# Main v12 jwilder 2019-04-15
version: "3.6"

networks:
  sister:
    name: sister
      external:true

services:
  #1
  couchdb:
    image: couchdb:2.3
    volumes:
      - ../data/home429c/:/home # folder for exported data, etc.
      - ../datasys/couch429c/:/opt/couchdb/data #TODO set this
      - ./docker/couchdb/:/opt/couchdb/etc/local.d
    ports:
      - "6212:5984" # no ssl
    env_file:
      - .env
    restart: always
    networks:
      - sister
    # labels:
    # - "virtual.host=couch.davidg.ml couch.dg24.tk couch-208-168-7-24.nip.io"
    # - "virtual.port=5984"
    # - "virtual.tls-email=d@gmail.com" # set to valid email to activate SSL
    # - "virtual.websockets" # enable websocket passthrough
    environment:
      - VIRTUAL_HOST=couch-208-168-7-24.nip.io
      - LETSENCRYPT_HOST=couch-208-168-7-24.nip.io
      - VIRTUAL_PORT=5984
      - LETSENCRYPT_EMAIL=d@gmail.com
    logging:
      driver: "json-file"
      options:
        max-size: "150k"
        max-file: "99"

  #2
  listo429c:
    # https://github.com/mikechernev/dockerised-php/blob/master/docker-compose.yml
    image: nginx:1.14
    # build:
    # context: ./
    # dockerfile: Dockerfile
    volumes:
      - ./listo429:/usr/share/nginx/html
    ports:
      # -  "82:80"
      - "6211:8084"
    restart: always
    networks:
      - sister
    # environment:
    # VIRTUAL_HOST: listo429c.david462.tk
    # VIRTUAL_HOST: a.davidg.ml
    # VIRTUAL_PORT: 80
    # labels:
    #   # caddy-gen info..
    #   - "virtual.host=l.davidg.ml"
    #   - "virtual.port=8084"
    #   - "virtual.tls-email=d@gmail.com" # set to valid email to activate SSL
    #   - "virtual.websockets" # enable websocket passthrough

  #4
  vpv445gb:
    # 192.168.88.60:6216
    image: nginx:1.14-alpine
    ports:
      - "6216:8083"
    expose:
      - "8083"
    volumes:
      - ./docker/nginx_vpv445g/nginxmain.conf:/etc/nginx/nginx.conf
      - ./docker/nginx_vpv445g/default.conf:/etc/nginx/conf.d/default.conf
      - ./vpv445g/dist:/usr/share/nginx/html
    restart: always
    networks:
      - sister
    # labels:
    #   # caddy-gen info..  t.dg24.tk t.david23.tk
    #   - "virtual.host=t.david462.tk t.davidg.ml t.dg24.tk vpv445g-208-168-7-24.nip.io"
    #   - "virtual.port=8083"
    #   - "virtual.tls-email=d@gmail.com" # set to valid email to activate SSL
    #   - "virtual.websockets" # enable websocket passthrough
    environment:
      # - VIRTUAL_HOST=t.david462.tk, t.davidg.ml, t.dg24.tk, vpv445g-208-168-7-24.nip.io
      - VIRTUAL_HOST=vpv445g-208-168-7-24.nip.io
      - LETSENCRYPT_HOST=vpv445g-208-168-7-24.nip.io
      - VIRTUAL_PORT=8083
      - LETSENCRYPT_EMAIL=d@gmail.com

  #5
  pgcouch429:
    # couch to pg job
    image: "node:10-slim"
    restart: always
    # user: "node"
    # environment:
    #   - NODE_ENV=production
    working_dir: /app
    volumes:
      - ./couch-to-postgres/:/app
    # expose:
    #   - "8081"
    depends_on:
      - couchdb
      - postgres429
      - listo429c
      - vpv445gb
      - sqlpad
      - adminer429
    # noworky.. command: sh .env &&  ./bin/index.js
    command: ./bin/index.js
    logging:
      driver: "json-file"
      options:
        max-size: "150k"
        max-file: "99"

  #6
  postgres429:
    # https://hub.docker.com/_/postgres/
    image: postgres:11
    restart: always
    # command: postgres -c listen_addresses = '*'
    env_file:
      - .env
    environment:
      # POSTGRES_PASSWORD: postgress
      CONFIGS: "listen_addresses:'*'"
      # https://github.com/syndbg/postgres-docker-cluster/blob/master/docker-compose.yml
      # in format variable1:value1[,variable2:value2[,...]]
      # used for pgpool.conf file
    ports:
      - 5433:5432
    volumes:
      - ../datasys/postgres429/:/var/lib/postgresql/data/ # folder for db internal data files.
      - .:/root # folder for scripts, etc.
      - ../data/data429/:/home # folder for exported data, etc.
      - ../docker/postgres/init/:/docker-entrypoint-initdb.d/ # init -- create db etc..
    networks:
      - sister

  #7
  sqlpad:
    # 192.168.88.60:6152
    image: sqlpad/sqlpad
    restart: always
    env_file:
      - .env
    ports:
      - "6152:3000"
    volumes:
      - ../datasys/sqlpad429/:/var/lib/sqlpad # folder for mysql's internal data files.
    #
    #   Noworky.. error 502 bad gateway.
    # labels:
    #   # caddy-gen info..  t.dg24.tk t.david23.tk
    #   - "virtual.host=spad.dg24.tk"
    #   - "virtual.port=3000"
    #   - "virtual.tls-email=d@gmail.com" # set to valid email to activate SSL
    #   - "virtual.websockets" # enable websocket passthrough
    environment:
      - VIRTUAL_HOST=spad-208-168-7-24.nip.io
      - LETSENCRYPT_HOST=spad-208-168-7-24.nip.io
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_EMAIL=d@gmail.com

  #9
  adminer429:
    # 192.168.88.60:8089
    image: adminer:4.6
    restart: always
    ports:
      - 8089:8080
    networks:
      - sister
    # labels:
    #   # caddy-gen info..  t.dg24.tk t.david23.tk
    #   - "virtual.host=admr.dg24.tk"
    #   - "virtual.port=8080"
    #   - "virtual.tls-email=d@gmail.com" # set to valid email to activate SSL
    #   - "virtual.websockets" # enable websocket passthrough
    environment:
      - VIRTUAL_HOST=admr-208-168-7-24.nip.io
      - LETSENCRYPT_HOST=admr-208-168-7-24.nip.io
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_EMAIL=d@gmail.com

  #10
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8090:80
    networks:
      - sister
    env_file:
      - .env

  #15
  maria:
    image: mariadb:10.3
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    env_file:
      - .env
    ports:
      - "6306:3306"
    volumes:
      - ../datasys/maria429/:/var/lib/mysql/ # folder for mysql's internal data files.
      - .:/root # folder for scripts, etc.
      - ../data/maria429/:/home # folder for exported data, etc.
    networks:
      - sister
    # https://medium.freecodecamp.org/how-to-setup-log-rotation-for-a-docker-container-a508093912b2
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"

  #15
  nextcl:
    # 192.168.3.30:6218/phpi.php
    image: nextcloud:15.0.5-apache
    ports:
      - 6218:80
    depends_on:
      - maria
    volumes:
      - ../datasys/nextcl429html/:/var/www/html
      #- ./docker/nextcloud/php.ini-production:/usr/local/etc/php/php.ini-production
      - ./docker/nextcloud/phpdg.ini:/usr/local/etc/php/conf.d/phpdg.ini
    restart: always
    env_file:
      - .env
    networks:
      - sister
    logging:
      driver: "json-file"
      options:
        max-size: "250k"
        max-file: "100"
    # # https://github.com/nextcloud/docker/issues/593 mysql_pass is not in docs for example.
    # labels:
    #   # caddy-gen info..
    #   - "virtual.host=nc.dg24.tk nc-208-168-7-24.nip.io"
    #   - "virtual.port=80"
    #   - "virtual.tls-email=d@gmail.com" # set to valid email to activate SSL
    #   - "virtual.websockets" # enable websocket passthrough
    environment:
      - VIRTUAL_HOST=nc-208-168-7-24.nip.io
      - LETSENCRYPT_HOST=nc-208-168-7-24.nip.io
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=d@gmail.com
